### ISSUE TITLE
Layout of data, program and work directories

### ISSUE THREAD

**Issue by vuw-ecs-kevin** [datacarpentry/cloud-genomics#20] opened 2017-10-03 22:49 UTC
Wanted to start by saying that I appreciate that the current lesson 
content is derived from lessons already given, and also that I am 
coming at things from the (clearly biased!) viewpoint of an adminstrator 
of  a **shared** HPC compute resource. I also note that there are two 
different directory layouts  between the "Single Analysis" episodes and 
the "Connecting to a  Remote Instance" episode, although the latter is not 
currently fleshed out with the actual commands one would run to perform
the example analysis.

With the above in mind then, what I picked up on, when running through 
the material for myself, is that, within this directory layout

```
/home/ec2-user/
└── data
    ├── FastQC
    │   ├── fastqc               
    │   └── ...                 
    ├── SRR                     
    │   ├── SRR447649_1.fastq 
    │   ├── SRR447649_2.fastq
    │   ├── SRR447649_3.fastq
    │   ├── SRR519926_1.fastq    
    │   └── SRR519926_2.fastq    
    └── Trimmomatic-0.32
        ├── adapters
        ├── LICENSE
        └── trimmomatic-0.32.jar 
```

 the user is encouraged to 

```
cd ~/data/SRR
```

before running their programs on the data, and although they are told
to create the sub directory `qc`, that's merely because the `FastQC`
program doesn't create one automatically.

I'd suggest that this, operating within the "source" directory, is not 
something to be encouraged, and would instead suggest that the 
user might be instructed to 

1. make a "work" directory in which to do their work, outside of the 
   "source data" and the "program" areas
   (indeed, it's a shame that the top-level directory is named `data`)
2. that they are then shown how to invoke the programs so that they  
    are obviously operating on source data outside of their "work area"
3. that they be explicitly told that their "work area" is unlikely to be 
    persistent, and that the next time they connect to a resource they
   may be starting from the original 

I belive this approach to have a number of benefits (and not just
to the likes of administrators of shared HPC resources like me!):

1. It espouses the ideas of "Reproducible Science" in that there is
    clearly defined "source data", which gets manipulated via a workflow
    processing pipeline (in the FastQC example the processing pipeline
    is just the one program) to produce "output data", and that these
    should not all be mingled in together.
2. It introduces/reinforces the notion that when using "remote" computational
    resources, there may already be "read-only" copies of centrally maintained 
    copies of reference data against which to work, and centrally maintained 
    copies of software packages with which to work, rather than everyone having 
    their own copy of everything.
3. It reinforces the idea that those parts of the "output" data which are **of interest** 
    and/or are **required for furure processing** should be moved out of the
   "work area"  when one has finished the parts of the work that they are produced
   by or needed for.
 
I note that in the "Trinnomatic section" further into the lesson, the user will be told 
to create a seperate directory for the results of the first part of that process, so would
suggest that making a directory within which to do **all** of the work is not that far 
removed from what's already there.

Couple of other things:

1. I'd also like to suggest that the `FastQC` program directory be given a version number, 
akin to the one visible on the `Trinnomatic` program directory as, again, this suggests
that specifiying the **actual** version of a program is a "good thing" (which, in terms of
reproducible science, it nearly always is).

2. Move the `--outdir qc` option so that it comes before the list of input files,
   which more closely matches the "command synopsis" that ones sees when
   typing `fastqc --help`

The commands to be folded into the lesson would thus be as follows

```
mkdir ~/work
cd ~/work

mkdir qc
~/data/FastQC-0.11.4/fastqc  --outdir qc ~/data/SRR/SRR519926_*.fastq
```

Hoping that some of this is useful,
Kevin

--
Kevin M. Buckley

eScience Consultant
School of Engineering and Computer Science
Victoria University of Wellington
New Zealand

**Comment by ACharbonneau** [comment] 2017-10-04 15:46
I agree with your assessment, however I think the fix for this module is actually just to drop this whole section, and make sure that your ideas are implemented in the correct places: 
 - The work directory and not running from source are excellent points, and belong in the 'Project Management' and 'File system' modules respectively.
 - The points about running FastQC more like the documentation and in a reproducible way belong in 'Working with Files'

This module should be focused on how to access various cloud resources, not on how to run specific programs or navigate the file systems. Once we get them on cloud resources, they'll all be on UNIX based servers, and the other modules are to teach them how to use them. We just get them there.

**Comment by devbioinfoguy** [comment] 2017-10-19 12:17
Agreed. I believe directory layout should be bumped up to a higher level (likely), and not just the one module's problem, as the layout will affect all modules. AGain, I think we need @tracykteal and/or @ErinBecker to chime in on this, or the DC Genomics Overview Committee.

-Bob

**Comment by tracykteal** [comment] 2017-10-24 21:44
@vuw-ecs-kevin thanks. This is a really good and important comment. You are right that is better practice to do things like create a 'work' directory. Because this change would impact many other areas of the lesson, and a need for a new instance, for the release coming up in a couple weeks, we'll use the existing version. But, this is something we should consider overall for the next set of updates. I'm going to tag this issue 'post-release' so we're sure to keep track of it. 

I think we should teach things this way, but I admit I am a bit conflicted on this, because I know many bioinformatics programs don't handle being run from outside their own directory very well without consistently using global path names, especially ones that are run interactively. I tried setting other path names for one bioinformatics program that I teach, and there ended up being a lot of issues. So, I think we just have to be thoughtful about how we present this approach and really emphasizing paths in our teaching.

**Comment by vuw-ecs-kevin** [comment] 2017-10-25 00:17
@tracykteal, as regards

> Because this change would impact many other areas of the lesson, and a need for a new
> instance, for the release coming up in a couple weeks, we'll use the existing version.

I'm getting the impression that most of my comments, as regards the lesson content
viisble at http://www.datacarpentry.org/cloud-genomics/ are arising from my unfamilairty,
both with the provenance of that content, and with the direction that the bioinformaticians 
who /wrote/are rewriitng/ the lesson are currently taking, and are hence being answered 
in pretty much the same way.

It thus seems prudent for me to wait until after the release and then start my inspection
again, once any unwanted content has been removed; any required content has been 
manatined, and such changes as thought necessary to the presentation layer of the 
lesson, have been introduced.

>  I'm going to tag this issue 'post-release' so we're sure to keep track of it.

+1

> ... because I know many bioinformatics programs don't handle being run from
> outside their own directory ...

Yes, there are a lot of poorly written bioinformatics programs, that don't allow for 
run-time customisation, already out there, and not doubt many more in the pipeline.

**Closed as completed** 2017-11-13 17:29 UTC
